[package]
name = "planetviewer"
version = "0.1.0"
description = "planetviewer"
authors = ["Bamboooz"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-global-shortcut = "2"
